import type { DocPage } from '../types';

export const proBranding: DocPage = {
  slug: 'pro-branding',
  title: 'Report Branding',
  description: 'Add your company logo, name, and custom styling to generated reports.',
  isPro: true,
  sections: [
    {
      heading: 'Overview',
      body: [
        'Report branding lets you customise the report header with your company logo, name, and tagline. This is particularly useful when sharing reports with stakeholders, clients, or cross-functional teams who expect a polished, professional presentation.',
      ],
    },
    {
      heading: 'Logo Configuration',
      body: [
        'Add your company logo to the report header. The logo can be a local file path or a URL. Local files are embedded as base64, so the report remains self-contained.',
      ],
      code: {
        language: 'typescript',
        content: `['playwright-smart-reporter', {
  brandingLogo: './assets/company-logo.svg',
  // or use a URL
  // brandingLogo: 'https://cdn.example.com/logo.svg',
}]`,
      },
      note: {
        type: 'info',
        content: 'SVG logos are recommended for best quality at all screen sizes. PNG and JPEG are also supported. Maximum file size is 500KB.',
      },
    },
    {
      heading: 'Company Name and Tagline',
      body: [
        'Display your company name alongside or below the logo. An optional tagline provides additional context.',
      ],
      code: {
        language: 'typescript',
        content: `['playwright-smart-reporter', {
  brandingLogo: './assets/logo.svg',
  brandingName: 'Acme Corp',
  brandingTagline: 'Quality Engineering',
}]`,
      },
    },
    {
      heading: 'Custom Header and Footer',
      body: [
        'Add custom HTML content to the report header and footer. This is useful for disclaimers, build information links, or team contact details.',
      ],
      code: {
        language: 'typescript',
        content: `['playwright-smart-reporter', {
  brandingHeader: '<div class="custom-header">Internal — Do Not Distribute</div>',
  brandingFooter: '<p>Generated by QA Team | Contact: qa@example.com</p>',
}]`,
      },
      note: {
        type: 'warning',
        content: 'Custom HTML is sanitised to prevent XSS. Script tags and event handlers are stripped automatically.',
      },
    },
    {
      heading: 'Brand Colour Integration',
      body: [
        'Combine branding with the ocean theme for a fully branded report experience.',
      ],
      code: {
        language: 'typescript',
        content: `['playwright-smart-reporter', {
  theme: 'ocean',
  themeOptions: {
    primaryColor: '#0052cc',
    accentColor: '#ff5630',
  },
  brandingLogo: './assets/logo.svg',
  brandingName: 'Acme Corp',
  brandingTagline: 'E2E Test Report',
}]`,
      },
      list: {
        items: [
          'Logo appears in the top-left corner of the header',
          'Company name renders next to the logo in the configured primary colour',
          'Tagline appears below the company name in a lighter weight',
          'Footer content renders at the bottom of every page/section',
        ],
        icon: 'check',
      },
    },
    {
      heading: 'Branding in Exports',
      body: [
        'Branding elements carry through to all export formats. PDF exports include the logo on the cover page, JUnit exports include the company name in the metadata, and JSON exports include branding in the report metadata object.',
      ],
      note: {
        type: 'pro',
        content: 'Report branding requires a Pro license. Without a license, branding options are silently ignored.',
      },
    },
  ],
};
