export default function Terms() {
  return (
    <article className="prose-legal">
      <h1 className="text-3xl sm:text-4xl font-bold text-white mb-2 tracking-tight">
        Terms of Service
      </h1>
      <p className="text-slate-500 text-sm mb-10">Last updated: February 2026</p>

      <p className="text-slate-300 mb-8 leading-relaxed">
        By using playwright-smart-reporter or the stagewright.dev website you
        agree to these terms. If you do not agree, do not use the service.
      </p>

      <Section title="Service Description">
        <p className="text-slate-400 leading-relaxed">
          StageWright provides the playwright-smart-reporter npm package (an
          open-source Playwright custom reporter) and a managed AI analysis
          proxy for paid license holders. The reporter generates self-contained
          HTML test reports.
        </p>
      </Section>

      <Section title="License Tiers">
        <ul className="list-disc pl-5 space-y-2 text-slate-400">
          <li>
            <strong className="text-slate-300">Community (Local)</strong> — free,
            MIT-licensed. Includes the full HTML report and all community
            features.
          </li>
          <li>
            <strong className="text-slate-300">Starter / Pro</strong> —
            commercial licenses purchased via LemonSqueezy. These unlock AI
            failure analysis, additional themes, exports, quality gates, and
            other premium features as described on the pricing page.
          </li>
        </ul>
      </Section>

      <Section title="Acceptable Use">
        <p className="text-slate-400 leading-relaxed mb-3">
          You agree not to:
        </p>
        <ul className="list-disc pl-5 space-y-2 text-slate-400">
          <li>Abuse, overload, or interfere with the AI analysis endpoint.</li>
          <li>Circumvent rate limits or license validation.</li>
          <li>Use the service for any unlawful purpose.</li>
          <li>Share, resell, or redistribute license keys.</li>
        </ul>
      </Section>

      <Section title="Intellectual Property">
        <p className="text-slate-400 leading-relaxed">
          Reports generated by the reporter are yours. The reporter source code
          is released under the MIT licence. Premium features are subject to the
          commercial licence granted with your Starter or Pro subscription.
        </p>
      </Section>

      <Section title="Limitation of Liability">
        <p className="text-slate-400 leading-relaxed">
          The service is provided "as is" without warranty of any kind. We do
          not guarantee the accuracy, completeness, or usefulness of AI failure
          analysis. To the fullest extent permitted by law, StageWright shall
          not be liable for any indirect, incidental, or consequential damages
          arising from your use of the service.
        </p>
      </Section>

      <Section title="Termination">
        <p className="text-slate-400 leading-relaxed">
          We may revoke a commercial licence if these terms are violated. The
          free community tier remains available regardless. You may cancel your
          subscription at any time through LemonSqueezy.
        </p>
      </Section>

      <Section title="Changes to These Terms">
        <p className="text-slate-400 leading-relaxed">
          We may update these terms from time to time. Continued use of the
          service after changes are published constitutes acceptance of the
          revised terms.
        </p>
      </Section>

      <Section title="Contact">
        <p className="text-slate-400 leading-relaxed">
          Questions about these terms? Email{' '}
          <a
            href="mailto:support@stagewright.dev"
            className="text-green-400 hover:text-green-300 transition-colors"
          >
            support@stagewright.dev
          </a>
          .
        </p>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-xl font-semibold text-white mb-3">{title}</h2>
      {children}
    </section>
  );
}
